/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;

import java.awt.Color;
import java.util.List;
import javax.persistence.*;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Muaz Ahmed
 */
public class giris_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form giris_ekrani
     */
    public giris_ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKullanıcı_adı = new javax.swing.JTextField();
        jButtonGiris = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelhata = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonSifreUnutmak = new javax.swing.JButton();
        jRadioButtunMudur = new javax.swing.JRadioButton();
        jRadioButtonPersonel = new javax.swing.JRadioButton();
        jLabelMudurPersonel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jButtonGiris.setText("Sign in");
        jButtonGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirisActionPerformed(evt);
            }
        });

        jButtonExit.setText("Close");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonSifreUnutmak.setText("Forgot password");
        jButtonSifreUnutmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSifreUnutmakActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtunMudur);
        jRadioButtunMudur.setText("Manager");
        jRadioButtunMudur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtunMudurActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPersonel);
        jRadioButtonPersonel.setText("Employee");
        jRadioButtonPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersonelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButtonExit)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSifreUnutmak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelhata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGiris))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPasswordField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtunMudur)
                                .addGap(159, 159, 159)
                                .addComponent(jRadioButtonPersonel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldKullanıcı_adı)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMudurPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtunMudur)
                    .addComponent(jRadioButtonPersonel)
                    .addComponent(jLabelMudurPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKullanıcı_adı, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonExit)
                        .addComponent(jButtonGiris)
                        .addComponent(jLabelhata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSifreUnutmak))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jRadioButtunMudurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtunMudurActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtunMudurActionPerformed

    private void jRadioButtonPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersonelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonPersonelActionPerformed

    
    private void jButtonGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirisActionPerformed
        // TODO add your handling code here:
//        EntityManagerFactory emf=Persistence.createEntityManagerFactory("GorevPU");
        if (jRadioButtunMudur.isSelected()&&jTextFieldKullanıcı_adı.getText().toLowerCase().equals("moaaz")&&jPasswordField.getText().toString().toLowerCase().equals("123")) {
            new ana_Menu().setVisible(true);
            this.setVisible(false);
        }
         else if (jRadioButtonPersonel.isSelected()) {
            EntityManagerFactory emf=Persistence.createEntityManagerFactory("GorevPU");
            EntityManager em=emf.createEntityManager();
            Query q =em.createQuery("select p from Personel p where p.adi= :pisim");
            em.getTransaction().begin();
            q.setParameter("pisim", jTextFieldKullanıcı_adı.getText().toLowerCase());
            List <Personel> personeller=q.getResultList();
            Personel_gorevleri person=new Personel_gorevleri(jTextFieldKullanıcı_adı.getText().toLowerCase());
            for (Personel personel : personeller) {
                if (personel.getSifre().toLowerCase().equals(jPasswordField.getText().toLowerCase())) {
                    person.jLabelId.setText(personel.getPersonelId().toString());
                    person.jLabelIsim.setText(personel.getAdi());
                    person.jLabelSoyadi.setText(personel.getSoyadi());
                    person.setVisible(true);
                    this.setVisible(false);
                    em.getTransaction().commit();
                }else {
                    jLabelhata.setForeground(Color.red);
                    jLabelhata.setBackground(Color.WHITE);
                    jLabelhata.setText("Hatalı bilgi girdiniz");
                }
            }
        }else {
            jLabelhata.setForeground(Color.red);
            jLabelhata.setBackground(Color.WHITE);
            jLabelhata.setText("Lütfen bir tür seçiniz");
        }
    }//GEN-LAST:event_jButtonGirisActionPerformed

    private void jButtonSifreUnutmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSifreUnutmakActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSifreUnutmakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGiris;
    private javax.swing.JButton jButtonSifreUnutmak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMudurPersonel;
    private javax.swing.JLabel jLabelhata;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonPersonel;
    private javax.swing.JRadioButton jRadioButtunMudur;
    private javax.swing.JTextField jTextFieldKullanıcı_adı;
    // End of variables declaration//GEN-END:variables
}
