/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;

import static Gorev.yeni_gorev_olusturma.jCalendar2;
import java.awt.Color;
import java.sql.*;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Muaz Ahmed
 */
public class gorev_duzeltme extends javax.swing.JFrame {

    /**
     * Creates new form gorev_duzeltmek
     */
    public gorev_duzeltme() {
        initComponents();
        EntityManagerFactory emfP = Persistence.createEntityManagerFactory("GorevPU");
        EntityManager emP = emfP.createEntityManager();
        Query qP = emP.createQuery("select p from Personel p");
        List<Personel> personeller = qP.getResultList();
        EntityManagerFactory emfD = Persistence.createEntityManagerFactory("GorevPU");
        EntityManager emD = emfD.createEntityManager();
        Query qD = emD.createQuery("select d from Departman d");
        List<Departman> Departmanlar = qD.getResultList();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        jLabelGorevNo.setForeground(Color.BLUE);
        jComboBoxGorevTipi.setForeground(Color.BLUE);
        jComboBoxOncelik.setForeground(Color.BLUE);
        jComboBoxSurec.setForeground(Color.BLUE);
        jTextField_konu.setForeground(Color.BLUE);
        jTextAreanot.setForeground(Color.BLUE);
//        this.setExtendedState(this.MAXIMIZED_BOTH);
        jComboBoxGorevTipi.removeAllItems();
        jComboBoxOncelik.removeAllItems();
        jComboBoxSurec.removeAllItems();
        jComboBoxDepartman.removeAllItems();
        jComboBoxPersonel.removeAllItems();
        jComboBoxGorevTipi.addItem("Tahsilat");
        jComboBoxGorevTipi.addItem("Cari mutbakat Gonder");
        jComboBoxSurec.addItem("Tahsilat Yapıldı");
        jComboBoxSurec.addItem("Gonderilecek");
        jComboBoxOncelik.addItem("Normal");
        jComboBoxOncelik.addItem("Yuksek");
        for (Personel person : personeller) {
            jComboBoxPersonel.addItem(person.getAdi());
        }
        for (Departman Departman : Departmanlar) {
            jComboBoxDepartman.addItem(Departman.getAdi());
        }
    }
//        catch (SQLException ex) {
//            Logger.getLogger(gorev_duzeltme.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGorev_No = new javax.swing.JLabel();
        jLabelhata = new javax.swing.JLabel();
        jLabelGorev_Tipi = new javax.swing.JLabel();
        jComboBoxGorevTipi = new javax.swing.JComboBox();
        jLabelSurec = new javax.swing.JLabel();
        jComboBoxSurec = new javax.swing.JComboBox();
        jLabelOncelik = new javax.swing.JLabel();
        jComboBoxOncelik = new javax.swing.JComboBox();
        jCalendar = new com.toedter.calendar.JCalendar();
        jButtonAnaMenu = new javax.swing.JButton();
        jLabel_not = new javax.swing.JLabel();
        jLabel_Konu = new javax.swing.JLabel();
        jTextField_konu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreanot = new javax.swing.JTextArea();
        jButtonguncelleme = new javax.swing.JButton();
        jLabelGorevNo = new javax.swing.JLabel();
        jButtonCikis = new javax.swing.JButton();
        jLabel_Tamamlama = new javax.swing.JLabel();
        jComboBoxPersonel = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDepartman = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGorev_No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGorev_No.setText("Job NO :");

        jLabelGorev_Tipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGorev_Tipi.setText("Job tybe");

        jComboBoxGorevTipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSurec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSurec.setText("Time");

        jComboBoxSurec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelOncelik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOncelik.setText("Priority");

        jComboBoxOncelik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAnaMenu.setText("Main menu");
        jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenuActionPerformed(evt);
            }
        });

        jLabel_not.setText("Note");

        jLabel_Konu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Konu.setText("Subject");

        jTextAreanot.setColumns(20);
        jTextAreanot.setRows(5);
        jScrollPane1.setViewportView(jTextAreanot);

        jButtonguncelleme.setText("Update");
        jButtonguncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguncellemeActionPerformed(evt);
            }
        });

        jButtonCikis.setText("Exit");
        jButtonCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCikisActionPerformed(evt);
            }
        });

        jLabel_Tamamlama.setText("Employee");

        jComboBoxPersonel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPersonelActionPerformed(evt);
            }
        });

        jLabel1.setText("department");

        jComboBoxDepartman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Tamamlama, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGorev_No, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGorev_Tipi)
                            .addComponent(jLabel_Konu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_not, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGorevNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabelhata, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonCikis)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBoxGorevTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelSurec)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxSurec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_konu)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(311, 311, 311)
                                            .addComponent(jLabelOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBoxOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jComboBoxPersonel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonAnaMenu)))
                                .addComponent(jButtonguncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabelhata, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGorev_No, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGorevNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGorev_Tipi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGorevTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSurec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnaMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_konu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Konu, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel_not))))
                    .addComponent(jCalendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tamamlama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jButtonguncelleme)
                .addGap(50, 50, 50)
                .addComponent(jButtonCikis)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        new ana_Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed

    private void jButtonguncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguncellemeActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            String s = "UPDATE GOREVLER SET GOREV_TIPI=? , SUREC=? , ONCELIK=? , KONU=? , GOREV_NOTU=? , TAMAMLAMA=? , PERSONEL_ISIMI=? , DEPARTMAN=? , TARIH=? WHERE GOREV_ID=?";
            PreparedStatement pstmt = con.prepareStatement(s);
            pstmt.setString(1, jComboBoxGorevTipi.getSelectedItem().toString());
            pstmt.setString(2, jComboBoxSurec.getSelectedItem().toString());
            pstmt.setString(3, jComboBoxOncelik.getSelectedItem().toString());
            pstmt.setString(4, jTextField_konu.getText());
            pstmt.setString(5, jTextAreanot.getText().toString());
            pstmt.setInt(6, 0);
            pstmt.setString(7, jComboBoxPersonel.getSelectedItem().toString());
            pstmt.setString(8, jComboBoxDepartman.getSelectedItem().toString());
            pstmt.setDate(9, Date());
            pstmt.setInt(10, Integer.parseInt(jLabelGorevNo.getText()));
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "görev düzenlendi");
            new gorev_listesi().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(gorev_listesi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonguncellemeActionPerformed

    public static java.sql.Date Date() {
        java.util.Calendar cal = Calendar.getInstance();
        java.util.Date utilDate = jCalendar.getDate(); // your util date
        cal.setTime(utilDate);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        java.sql.Date sqlDate = new java.sql.Date(cal.getTime().getTime());
        return sqlDate;
   }  
    private void jButtonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCikisActionPerformed
        // TODO add your handling code here:
        new giris_ekrani().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCikisActionPerformed

    private void jComboBoxPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPersonelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPersonelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gorev_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gorev_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gorev_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gorev_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gorev_duzeltme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonCikis;
    private javax.swing.JButton jButtonguncelleme;
    public static com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JComboBox jComboBoxDepartman;
    public static javax.swing.JComboBox jComboBoxGorevTipi;
    public static javax.swing.JComboBox jComboBoxOncelik;
    private javax.swing.JComboBox jComboBoxPersonel;
    public static javax.swing.JComboBox jComboBoxSurec;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelGorevNo;
    private javax.swing.JLabel jLabelGorev_No;
    private javax.swing.JLabel jLabelGorev_Tipi;
    private javax.swing.JLabel jLabelOncelik;
    private javax.swing.JLabel jLabelSurec;
    private javax.swing.JLabel jLabel_Konu;
    private javax.swing.JLabel jLabel_Tamamlama;
    private javax.swing.JLabel jLabel_not;
    private javax.swing.JLabel jLabelhata;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreanot;
    public static javax.swing.JTextField jTextField_konu;
    // End of variables declaration//GEN-END:variables
}
