/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;

import java.awt.Color;
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muaz Ahmed
 */
public class gorev_listesi extends javax.swing.JFrame {
    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form cari_hareket_ekrani_entegrasyonu
     */
    public gorev_listesi() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.getContentPane().setBackground(Color.LIGHT_GRAY);
            jTable_gorev_listesi.setForeground(Color.blue);
            jTable_gorev_listesi.setBackground(Color.WHITE);
            jTable_gorev_listesi.setModel(dtm);
            String []kolomnisimleri={"Gorev No","Tipi","Süreç","Öncelik","Konu","Not","Tamamlama","Personel İsmi","Departman","Tarih"};
            dtm.setColumnIdentifiers(kolomnisimleri);
            this.setExtendedState(this.MAXIMIZED_BOTH);
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample","app","app");
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM GOREVLER");
            ResultSet rs= pstmt.executeQuery();
            while (rs.next()) {                
                dtm.addRow(new Object []{rs.getInt(1)+"",rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(gorev_listesi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_gorev_listesi = new javax.swing.JTable();
        jButtonSil = new javax.swing.JButton();
        jButtonYenileme = new javax.swing.JButton();
        jButtonAnaMenu = new javax.swing.JButton();
        jButtonDuzelt = new javax.swing.JButton();
        jButtonCikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_gorev_listesi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    jTable_gorev_listesi.setRowHeight(25);
    jScrollPane1.setViewportView(jTable_gorev_listesi);

    jButtonSil.setText("Delete");
    jButtonSil.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSilActionPerformed(evt);
        }
    });

    jButtonYenileme.setText("Refresh");
    jButtonYenileme.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonYenilemeActionPerformed(evt);
        }
    });

    jButtonAnaMenu.setText("Main menu");
    jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAnaMenuActionPerformed(evt);
        }
    });

    jButtonDuzelt.setText("Edit");
    jButtonDuzelt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonDuzeltActionPerformed(evt);
        }
    });

    jButtonCikis.setText("Exit");
    jButtonCikis.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCikisActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButtonYenileme)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonSil)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonDuzelt)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1337, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCikis)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(90, 90, 90)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSil)
                    .addComponent(jButtonYenileme)
                    .addComponent(jButtonDuzelt))
                .addComponent(jButtonAnaMenu, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jButtonCikis)
            .addGap(25, 25, 25))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
            // TODO add your handling code here:
            try {
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                con.setAutoCommit(false);
                String s = "DELETE FROM GOREVLER WHERE GOREV_ID=?";
                PreparedStatement pstmt = con.prepareStatement(s);
                pstmt.setInt(1, Integer.parseInt(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 0).toString()));
                pstmt.executeUpdate();
                con.commit();
                dtm.removeRow(jTable_gorev_listesi.getSelectedRow());
            }
            catch (ArrayIndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this, "Lütfen bir görev seçiniz !");
            }
            catch (SQLException ex) {
                Logger.getLogger(gorev_listesi.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jButtonYenilemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYenilemeActionPerformed
        // TODO add your handling code here:
        new gorev_listesi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonYenilemeActionPerformed

    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        new ana_Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed
    
    private void jButtonDuzeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDuzeltActionPerformed
        try {
            gorev_duzeltme g = new gorev_duzeltme();
            g.jLabelGorevNo.setText(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 0).toString());
            g.jComboBoxGorevTipi.setSelectedItem(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 1));
            g.jComboBoxSurec.setSelectedItem(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 2));
            g.jComboBoxOncelik.setSelectedItem(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 3));
            g.jTextField_konu.setText(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 4).toString());
            g.jTextAreanot.setText(jTable_gorev_listesi.getValueAt(jTable_gorev_listesi.getSelectedRow(), 5).toString());
            g.setVisible(true);
            this.setVisible(false);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Lütfen bir görev seçiniz !");
        }
    }//GEN-LAST:event_jButtonDuzeltActionPerformed

    private void jButtonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCikisActionPerformed
        // TODO add your handling code here:
        new giris_ekrani().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gorev_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gorev_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gorev_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gorev_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gorev_listesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonCikis;
    private javax.swing.JButton jButtonDuzelt;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JButton jButtonYenileme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_gorev_listesi;
    // End of variables declaration//GEN-END:variables
}
