/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;

import static Gorev.yeni_personel_ekleme.toBufferedImage;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Muaz Ahmed
 */
public class personel_duzeltme extends javax.swing.JFrame {

    /**
     * Creates new form personel_duzeltme
     */
    public personel_duzeltme() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        jComboBoxDepartman.removeAllItems();
        jComboBoxSube.removeAllItems();
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample ", "app", "app");
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM DEPARTMAN");
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                jComboBoxDepartman.addItem(rs.getString(2));
            }
            Connection con1 = DriverManager.getConnection("jdbc:derby://localhost:1527/sample ", "app", "app");
            PreparedStatement pstmt1 = con1.prepareStatement("SELECT * FROM SUBE");
            ResultSet rs1 = pstmt1.executeQuery();
            while (rs1.next()) {
                jComboBoxSube.addItem(rs1.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldMaas = new javax.swing.JTextField();
        jButtonPersonelGuncelle = new javax.swing.JButton();
        jComboBoxDepartman = new javax.swing.JComboBox();
        jComboBoxSube = new javax.swing.JComboBox();
        jLabelIdHatasi = new javax.swing.JLabel();
        jLabelmaasHatasi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonErkek = new javax.swing.JRadioButton();
        try {
            jButtonresim_ekleme =(javax.swing.JButton)java.beans.Beans.instantiate(getClass().getClassLoader(), "Gorev.yeni_personel_ekleme_jButtonresim_ekleme");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jRadioButtonBeyan = new javax.swing.JRadioButton();
        jLabelResim = new javax.swing.JLabel();
        jLabelResimHatasi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldsifre = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldSifreTekrar = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabelSifreHtasi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelsifre = new javax.swing.JLabel();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldSoyadi = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jButtonAnaMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPersonelGuncelle.setText("Update");
        jButtonPersonelGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelGuncelleActionPerformed(evt);
            }
        });

        jComboBoxDepartman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSube.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Password        :");

        jLabel8.setText("Password again :");

        jLabel9.setText("Gander            :");

        buttonGroup1.add(jRadioButtonErkek);
        jRadioButtonErkek.setText("Man");

        jButtonresim_ekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresim_eklemeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBeyan);
        jRadioButtonBeyan.setText("Woman");

        jLabelResim.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID                   :");

        jLabel3.setText("Name              :");

        jLabel4.setText("Surname         :");

        jLabel5.setText("Salary             :");

        jLabel6.setText("Department    :   ");

        jLabel7.setText("Branch            : ");

        jButtonAnaMenu.setText("Main menu");
        jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPersonelGuncelle)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnaMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSube, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButtonErkek)
                                .addGap(99, 99, 99)
                                .addComponent(jRadioButtonBeyan)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordFieldSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSifreHtasi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonresim_ekleme)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelmaasHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(jTextFieldAdi))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIdHatasi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPasswordFieldsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelsifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResim, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResimHatasi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelResim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResimHatasi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIdHatasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelmaasHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldsifre)
                                    .addComponent(jLabelsifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonresim_ekleme)
                    .addComponent(jPasswordFieldSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSifreHtasi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButtonErkek)
                    .addComponent(jRadioButtonBeyan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(jButtonPersonelGuncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnaMenu)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void setNull(){
        jLabelId.setText(null);
            jTextFieldAdi.setText(null);
            jTextFieldSoyadi.setText(null);
            jTextFieldMaas.setText(null);
            jComboBoxDepartman.setSelectedIndex(0);
            jComboBoxSube.setSelectedIndex(0);
            jLabelResim.setIcon(null);
            jPasswordFieldsifre.setText(null);
            jPasswordFieldSifreTekrar.setText(null);
            jLabelResimHatasi.setText(null);
    }
    private void jButtonPersonelGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelGuncelleActionPerformed
        // TODO add your handling code here:
        try {
            char[] password = jPasswordFieldsifre.getPassword();
            char[] passwordtekrar=jPasswordFieldSifreTekrar.getPassword();
            String sb = String.valueOf(password);
            String sbt = String.valueOf(passwordtekrar);
            if (sb.equals(sbt)) {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("GorevPU");
                EntityManager em = emf.createEntityManager();
                Query q=em.createQuery("UPDATE Personel p SET p.adi = :pAdi , p.soyadi = :pSoyadi , p.maas = :pMaas , p.departman = :pDepartman , p.sube = :pSube , p.cinsiyet = :pCinsiyet , p.sifre = :pSifre , p.sifretekrar = :pSifreTekrar , p.personelResimi = :pResim WHERE p.personelId = :pId");
                em.getTransaction().begin();
                q.setParameter("pId", Integer.parseInt(jLabelId.getText()));
                q.setParameter("pAdi", jTextFieldAdi.getText());
                q.setParameter("pSoyadi", jTextFieldSoyadi.getText());
                q.setParameter("pMaas", Integer.parseInt(jTextFieldMaas.getText()));
                q.setParameter("pDepartman", jComboBoxDepartman.getSelectedItem());
                q.setParameter("pSube", jComboBoxSube.getSelectedItem());
                if (jRadioButtonErkek.isSelected()) {
                    q.setParameter("pCinsiyet","Erkek");
                }
                else 
                    q.setParameter("pCinsiyet","Bayan");
                q.setParameter("pSifre", sb);
                q.setParameter("pSifreTekrar", sbt);
                q.setParameter("pResim", person_image);
                q.executeUpdate();
                em.getTransaction().commit();
                JOptionPane.showMessageDialog(this, "Personelin bilgileri düzenlendi");
            } else {
                jLabelSifreHtasi.setForeground(Color.red);
                jLabelSifreHtasi.setText("Şifre eşleşilmedi");
            }
            setNull();
        } catch (NumberFormatException ex) {
            jLabelmaasHatasi.setForeground(Color.red);
            jLabelmaasHatasi.setText("Lütfen geçerli maaş rakamı giriniz");
            jLabelIdHatasi.setForeground(Color.red);
            jLabelIdHatasi.setText("Lütfen geçerli personel numara giriniz");
            jLabelsifre.setForeground(Color.red);
            jLabelsifre.setText("Lütfen şifre alanı boş bırakmayınız");
        } catch (Exception e) {
            Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonPersonelGuncelleActionPerformed

    private void jButtonresim_eklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresim_eklemeActionPerformed
        jLabelResim.setText(null);
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        try {
            filename = f.getAbsolutePath();
            img = ImageIO.read(new File(f.getAbsolutePath()));
            Image image = img.getScaledInstance(jLabelResim.getWidth(), jLabelResim.getHeight(), img.SCALE_SMOOTH);
            dimg = toBufferedImage(image);
            ImageIcon icon1 = new ImageIcon(dimg);
            jLabelResim.setIcon(icon1);
            icon = icon1;
            jLabelResimHatasi.setText(null);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            jLabelResimHatasi.setForeground(Color.red);
            jLabelResimHatasi.setText("dosya yok ");
        } catch (NullPointerException e) {
            jLabelResimHatasi.setForeground(Color.red);
            jLabelResimHatasi.setText("resim seçilmemiş ! ");
        } catch (Exception e) {
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, e);
        }
        attach();
    }//GEN-LAST:event_jButtonresim_eklemeActionPerformed

    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        new ana_Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed
    BufferedImage img = null;
    BufferedImage dimg = null;
    ImageIcon icon;
//    public ImageIcon format=null;
    public String filename = null;
//    int s=0;
    public byte[] person_image = null;

    public void attach() {
//        JFileChooser ch=new JFileChooser();
//        ch.showOpenDialog(null);
//        File f=ch.getSelectedFile();
//        filename=f.getAbsolutePath();
        try {
            File image = new File(filename);
            FileInputStream fs = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fs.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personel_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personel_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personel_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personel_duzeltme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personel_duzeltme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonPersonelGuncelle;
    public static javax.swing.JButton jButtonresim_ekleme;
    public static javax.swing.JComboBox jComboBoxDepartman;
    public static javax.swing.JComboBox jComboBoxSube;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdHatasi;
    public static javax.swing.JLabel jLabelResim;
    private javax.swing.JLabel jLabelResimHatasi;
    private javax.swing.JLabel jLabelSifreHtasi;
    private javax.swing.JLabel jLabelmaasHatasi;
    private javax.swing.JLabel jLabelsifre;
    public static javax.swing.JPasswordField jPasswordFieldSifreTekrar;
    public static javax.swing.JPasswordField jPasswordFieldsifre;
    public static javax.swing.JRadioButton jRadioButtonBeyan;
    public static javax.swing.JRadioButton jRadioButtonErkek;
    public static javax.swing.JTextField jTextFieldAdi;
    public static javax.swing.JTextField jTextFieldMaas;
    public static javax.swing.JTextField jTextFieldSoyadi;
    // End of variables declaration//GEN-END:variables
}
