/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;

import static Gorev.Personel_.personelResimi;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.System.in;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Muaz Ahmed
 */
public class yeni_personel_ekleme extends javax.swing.JFrame {

    /**
     * Creates new form yeni_personel_ekleme
     */
    public yeni_personel_ekleme() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        jComboBoxDepartman.removeAllItems();
        jComboBoxSube.removeAllItems();
        try {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample ","app" ,"app");
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM DEPARTMAN");
            ResultSet rs=pstmt.executeQuery();
            while (rs.next()) {                
                jComboBoxDepartman.addItem(rs.getString(2));
            }
            Connection con1 =DriverManager.getConnection("jdbc:derby://localhost:1527/sample ","app" ,"app");
            PreparedStatement pstmt1=con1.prepareStatement("SELECT * FROM SUBE");
            ResultSet rs1=pstmt1.executeQuery();
            while (rs1.next()) {                
                jComboBoxSube.addItem(rs1.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        try {
            jButtonresim_ekleme =(javax.swing.JButton)java.beans.Beans.instantiate(getClass().getClassLoader(), "Gorev.yeni_personel_ekleme_jButtonresim_ekleme");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabelResim = new javax.swing.JLabel();
        jLabelResimHatasi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldSoyadi = new javax.swing.JTextField();
        jTextFieldMaas = new javax.swing.JTextField();
        jButtonPersonelEkle = new javax.swing.JButton();
        jComboBoxDepartman = new javax.swing.JComboBox();
        jComboBoxSube = new javax.swing.JComboBox();
        jLabelIdHatasi = new javax.swing.JLabel();
        jLabelmaasHatasi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonErkek = new javax.swing.JRadioButton();
        jRadioButtonBeyan = new javax.swing.JRadioButton();
        jPasswordFieldsifre = new javax.swing.JPasswordField();
        jPasswordFieldSifreTekrar = new javax.swing.JPasswordField();
        jLabelSifreHtasi = new javax.swing.JLabel();
        jLabelsifre = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonAnaMenu = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonresim_ekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresim_eklemeActionPerformed(evt);
            }
        });

        jLabelResim.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID                   :");

        jLabel3.setText("Name              :");

        jLabel4.setText("Surname         :");

        jLabel5.setText("Salary            :");

        jLabel6.setText("Department   :   ");

        jLabel7.setText("Branch           : ");

        jButtonPersonelEkle.setText("Save");
        jButtonPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelEkleActionPerformed(evt);
            }
        });

        jComboBoxDepartman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSube.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Password      :");

        jLabel8.setText("Password again    :");

        jLabel9.setText("Gander         :");

        buttonGroup1.add(jRadioButtonErkek);
        jRadioButtonErkek.setText("Man");

        buttonGroup1.add(jRadioButtonBeyan);
        jRadioButtonBeyan.setText("Woman");

        jButtonAnaMenu.setText("Main menu");
        jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelmaasHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAdi))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelIdHatasi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPasswordFieldsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelsifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(34, 34, 34)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordFieldSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSifreHtasi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResim, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jLabelResimHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButtonresim_ekleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnaMenu))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPersonelEkle)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSube, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButtonErkek)
                                .addGap(99, 99, 99)
                                .addComponent(jRadioButtonBeyan)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelResim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResimHatasi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdHatasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelmaasHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldsifre)
                                    .addComponent(jLabelsifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonresim_ekleme, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSifreHtasi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButtonErkek)
                    .addComponent(jRadioButtonBeyan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonPersonelEkle)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnaMenu)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static BufferedImage toBufferedImage(Image img) {
        if (img instanceof BufferedImage) {
            return (BufferedImage) img;
        }
        // Create a buffered image with transparency
        BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
        // Draw the image on to the buffered image
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();
        // Return the buffered image
        return bimage;
    }
    private void jButtonresim_eklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresim_eklemeActionPerformed
        jLabelResim.setText(null);
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        try {
            filename=f.getAbsolutePath();
            img = ImageIO.read(new File(f.getAbsolutePath()));
            Image image=img.getScaledInstance(jLabelResim.getWidth(), jLabelResim.getHeight(),img.SCALE_SMOOTH);
            dimg = toBufferedImage(image);
            ImageIcon icon1=new ImageIcon(dimg);
            jLabelResim.setIcon(icon1); 
            icon=icon1;
            jLabelResimHatasi.setText(null);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            jLabelResimHatasi.setForeground(Color.red);
            jLabelResimHatasi.setText("dosya yok ");
        } catch (NullPointerException e) {
            jLabelResimHatasi.setForeground(Color.red);
            jLabelResimHatasi.setText("resim seçilmemiş ! ");
        } catch (Exception e){
            Logger.getLogger(yeni_personel_ekleme.class.getName()).log(Level.SEVERE, null, e);
        }
        attach();
    }//GEN-LAST:event_jButtonresim_eklemeActionPerformed
    BufferedImage img = null;
    BufferedImage dimg = null;
    ImageIcon icon;
//    public ImageIcon format=null;
    public String filename=null;
//    int s=0;
    public byte[]person_image=null;
    public void attach(){
        try {
            File image =new File(filename);
            FileInputStream fs=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[]buf=new byte[1024];
            for (int readNum; (readNum=fs.read(buf))!=-1;) {
                bos.write(buf, 0, readNum);
            }
            person_image=bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    void setnull() {
        jTextFieldID.setText(null);
        jTextFieldAdi.setText(null);
        jTextFieldSoyadi.setText(null);
        jTextFieldMaas.setText(null);
        jComboBoxDepartman.setSelectedIndex(0);
        jComboBoxSube.setSelectedIndex(0);
        jLabelResim.setIcon(null);
        jPasswordFieldsifre.setText(null);
        jPasswordFieldSifreTekrar.setText(null);
        jLabelResimHatasi.setText(null);
    }
    private void jButtonPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelEkleActionPerformed
        // TODO add your handling code here:
        try {
            char[] password = jPasswordFieldsifre.getPassword();
            char[] passwordtekrar=jPasswordFieldSifreTekrar.getPassword();
            String sb = String.valueOf(password);
            String sbt = String.valueOf(passwordtekrar);
            if (sb.equals(sbt)) {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("GorevPU");
                EntityManager em = emf.createEntityManager();
                   em.getTransaction().begin();
                Personel p = new Personel();
                p.setPersonelId(Integer.parseInt(jTextFieldID.getText()));
                p.setAdi(jTextFieldAdi.getText().toLowerCase());
                p.setSoyadi(jTextFieldSoyadi.getText());
                p.setMaas(Integer.parseInt(jTextFieldMaas.getText()));
                p.setDepartman(jComboBoxDepartman.getSelectedItem().toString());
                p.setSube(jComboBoxSube.getSelectedItem().toString());
                p.setSifre(sb.toString());
                p.setSifretekrar(sbt.toString());
                p.setPersonelResimi(person_image);
                if (jRadioButtonErkek.isSelected()) {
                    p.setCinsiyet("Erkek");
                } else {
                    p.setCinsiyet("Bayan");
                }
                em.persist(p);
                em.getTransaction().commit();
                em.close();
                JOptionPane.showMessageDialog(this, "Yeni Personel eklendi");
            } else {
                jLabelSifreHtasi.setForeground(Color.red);
                jLabelSifreHtasi.setText("Şifre eşleşilmedi");
            }
        }
        catch (NumberFormatException ex) {
            jLabelmaasHatasi.setForeground(Color.red);
            jLabelmaasHatasi.setText("Lütfen geçerli maaş rakamı giriniz");
            jLabelIdHatasi.setForeground(Color.red);
            jLabelIdHatasi.setText("Lütfen geçerli personel numara giriniz");
            jLabelsifre.setForeground(Color.red);
            jLabelsifre.setText("Lütfen şifre alanı boş bırakmayınız");
        } 
        catch (Exception e ) {
            if (e.getClass().toString().equals("class javax.persistence.RollbackException")) {
                jLabelIdHatasi.setForeground(Color.red);
                jLabelIdHatasi.setText("Bu numarayla farklı kaydınız vardır");
            }
        }
        setnull();
    }//GEN-LAST:event_jButtonPersonelEkleActionPerformed

    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        new ana_Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed
 
    static JFileChooser fc;
    public static byte[]readImage() {
        InputStream is=null;
        byte[] bytes=null;
        try {
            File file=new File(fc.getSelectedFile().getAbsolutePath());
            is =new FileInputStream(file);
            //get the size of the file 
            long length =file.length();
            if (length >Integer.MAX_VALUE) {
                JOptionPane.showMessageDialog(null, "Dosya çok büyük");
                return null;
            }
            //create the byte array to hold the data
            bytes=new byte[(int)length];
            //read in the beyts
            int offset=0;
            int numRead=0;
            while (offset<bytes.length&&(numRead=is.read(bytes,offset,bytes.length-offset))>=0) {                
                offset+=numRead;
            }//ensure all the bytes have read in 
            is.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }finally{
            try {
                is.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        return bytes;
    }
    
    public static ImageIcon getscaledImage(String filename) {
        ImageIcon imageicon=new ImageIcon(filename);//load the image to the image icon
        Image image=imageicon.getImage();//transform it
        double h=100.0/imageicon.getIconHeight();//calculate w /h ratio
        Image newimage =image.getScaledInstance((int)(imageicon.getIconWidth()*h),
                (int)(imageicon.getIconHeight()*h), java.awt.Image.SCALE_SMOOTH);//scale it the smooth way
        return new ImageIcon(newimage);//transform it back
    }
    
//    public static ImageIcon getImage(){
//        fc=new JFileChooser();
//        FileFilter jpegFilter=new ExtensionFileFilter(null,new String []{"JPG","JPEG","PNG","GIF"});
//        fc.addChoosableFileFilter(jpegFilter);
//        fc.setFileFilter(jpegFilter);
//        int returnval=fc.showOpenDialog(null);
//        if (returnval==JFileChooser.APPROVE_OPTION) {
//            return getscaledImage(fc.getSelectedFile().getAbsolutePath());
//        }
//        return null;
//    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        String path = f.getAbsolutePath();
        jLabel1.setIcon(new ImageIcon(path));

        try {
            FileInputStream fin = new FileInputStream(f);
            int len = (int) f.length();
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample ","app" ,"app");
            PreparedStatement ps = con.prepareStatement("Insert into profile values(?)");

            ps.setBinaryStream(1, fin, len);
            int status = ps.executeUpdate();

            if (status > 0) {
                jLabelResimHatasi.setText("Successfully inserted in DB");
            } else {
                jLabelResimHatasi.setText("Image not inserted!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeni_personel_ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeni_personel_ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeni_personel_ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeni_personel_ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeni_personel_ekleme().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonPersonelEkle;
    public static javax.swing.JButton jButtonresim_ekleme;
    private javax.swing.JComboBox jComboBoxDepartman;
    private javax.swing.JComboBox jComboBoxSube;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdHatasi;
    private javax.swing.JLabel jLabelResim;
    private javax.swing.JLabel jLabelResimHatasi;
    private javax.swing.JLabel jLabelSifreHtasi;
    private javax.swing.JLabel jLabelmaasHatasi;
    private javax.swing.JLabel jLabelsifre;
    private javax.swing.JPasswordField jPasswordFieldSifreTekrar;
    private javax.swing.JPasswordField jPasswordFieldsifre;
    private javax.swing.JRadioButton jRadioButtonBeyan;
    private javax.swing.JRadioButton jRadioButtonErkek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMaas;
    private javax.swing.JTextField jTextFieldSoyadi;
    // End of variables declaration//GEN-END:variables
}
