/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gorev;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.lang.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Muaz Ahmed
 */
public class yeni_gorev_olusturma extends javax.swing.JFrame {
    DefaultListModel dlmP=new DefaultListModel();
    DefaultListModel dlmD=new DefaultListModel();
    /**
     * Creates new form yeni_gorev_olusturma
     */
    public yeni_gorev_olusturma() {
        initComponents();
        EntityManagerFactory emfP=Persistence.createEntityManagerFactory("GorevPU");
        EntityManager emP=emfP.createEntityManager();
        Query qP=emP.createQuery("select p from Personel p");
        List <Personel> personeller = qP.getResultList();
        EntityManagerFactory emfD=Persistence.createEntityManagerFactory("GorevPU");
        EntityManager emD=emfD.createEntityManager();
        Query qD=emD.createQuery("select d from Departman d");
        List <Departman> Departmanlar = qD.getResultList();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        jTextFieldGorev_No.setForeground(Color.BLUE);
        jComboBoxGorevTipi.setForeground(Color.BLUE);
        jComboBoxOncelik.setForeground(Color.BLUE);
        jComboBoxSurec.setForeground(Color.BLUE);
        jTextField_konu.setForeground(Color.BLUE);
        jTextAreanot.setForeground(Color.BLUE);
        jComboBoxGorevTipi.removeAllItems();
        jComboBoxOncelik.removeAllItems();
        jComboBoxSurec.removeAllItems();
        jComboBoxDepartman.removeAllItems();
        jComboBoxPersonel.removeAllItems();
        jComboBoxGorevTipi.addItem("Tahsilat");
        jComboBoxGorevTipi.addItem("Cari mutbakat Gonder");
        jComboBoxSurec.addItem("Tahsilat Yapıldı");
        jComboBoxSurec.addItem("Gonderilecek");
        jComboBoxOncelik.addItem("Normal");
        jComboBoxOncelik.addItem("Yuksek");
        for (Personel person : personeller) {
            jComboBoxPersonel.addItem(person.getAdi());
        }
        for (Departman Departman : Departmanlar) {
            jComboBoxDepartman.addItem(Departman.getAdi());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGorev_No = new javax.swing.JLabel();
        jTextFieldGorev_No = new javax.swing.JTextField();
        jLabelSurec = new javax.swing.JLabel();
        jComboBoxGorevTipi = new javax.swing.JComboBox();
        jLabelGorev_Tipi = new javax.swing.JLabel();
        jComboBoxSurec = new javax.swing.JComboBox();
        jLabelOncelik = new javax.swing.JLabel();
        jComboBoxOncelik = new javax.swing.JComboBox();
        jLabel_Konu = new javax.swing.JLabel();
        jLabel_not = new javax.swing.JLabel();
        jTextField_konu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreanot = new javax.swing.JTextArea();
        jLabel_Tamamlama = new javax.swing.JLabel();
        jButtonKaydet = new javax.swing.JButton();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabelhata = new javax.swing.JLabel();
        jButtonAnaMenu = new javax.swing.JButton();
        jButtonCikis = new javax.swing.JButton();
        jComboBoxPersonel = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDepartman = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGorev_No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGorev_No.setText("Job No :");
        getContentPane().add(jLabelGorev_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 81, 40));
        getContentPane().add(jTextFieldGorev_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabelSurec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSurec.setText("Time");
        getContentPane().add(jLabelSurec, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 40));

        jComboBoxGorevTipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxGorevTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 102, 140, -1));

        jLabelGorev_Tipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGorev_Tipi.setText("Job type");
        getContentPane().add(jLabelGorev_Tipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 40));

        jComboBoxSurec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxSurec, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 100, -1));

        jLabelOncelik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOncelik.setText("Priority");
        getContentPane().add(jLabelOncelik, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 43, 40));

        jComboBoxOncelik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxOncelik, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 80, -1));

        jLabel_Konu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Konu.setText("Subject");
        getContentPane().add(jLabel_Konu, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 150, 60, 14));

        jLabel_not.setText("Note");
        getContentPane().add(jLabel_not, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 30, -1));
        getContentPane().add(jTextField_konu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 430, 30));

        jTextAreanot.setColumns(20);
        jTextAreanot.setRows(5);
        jScrollPane1.setViewportView(jTextAreanot);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 430, 110));

        jLabel_Tamamlama.setText("Employee");
        getContentPane().add(jLabel_Tamamlama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 20));

        jButtonKaydet.setText("Save");
        jButtonKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 73, -1));
        getContentPane().add(jCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 350, -1));
        getContentPane().add(jLabelhata, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 44, 220, 40));

        jButtonAnaMenu.setText("main menu");
        jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, -1, -1));

        jButtonCikis.setText("Exit");
        jButtonCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCikisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, -1));

        jComboBoxPersonel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxPersonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 150, -1));

        jLabel1.setText("Department");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 80, 20));

        jComboBoxDepartman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxDepartman, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKaydetActionPerformed
        try {
            EntityManagerFactory emf=Persistence.createEntityManagerFactory("GorevPU");
            EntityManager em=emf.createEntityManager();
            Query q =em.createQuery("select g from Gorevler g where g.personelIsimi= :pgorevi ");
            q.setParameter("pgorevi", jComboBoxPersonel.getSelectedItem());
            List <Gorevler> gorevler=q.getResultList();
            int toplam = 0, sayac = 0;
            for (Gorevler gorev : gorevler) {
                sayac++;
                toplam += gorev.getTamamlama();
            }
            if (sayac <= 3||toplam>100) {
                jLabelhata.setText(null);
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                String s = "INSERT INTO GOREVLER(GOREV_ID,GOREV_TIPI,SUREC,ONCELIK,KONU,GOREV_NOTU,TAMAMLAMA,PERSONEL_ISIMI,DEPARTMAN,TARIH) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pstmt = con.prepareStatement(s);
                pstmt.setInt(1, Integer.parseInt(jTextFieldGorev_No.getText()));
                pstmt.setString(2, jComboBoxGorevTipi.getSelectedItem().toString());
                pstmt.setString(3, jComboBoxSurec.getSelectedItem().toString());
                pstmt.setString(4, jComboBoxOncelik.getSelectedItem().toString());
                pstmt.setString(5, jTextField_konu.getText());
                pstmt.setString(6, jTextAreanot.getText());
                pstmt.setInt(7, 0);
                pstmt.setString(8, jComboBoxPersonel.getSelectedItem().toString());
                pstmt.setString(9, jComboBoxDepartman.getSelectedItem().toString());
                pstmt.setDate(10, Date());
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Yeni göreviniz eklendi");
            } else {
                    JOptionPane.showMessageDialog(this, "Bu personele yeni bir görev eklenemiyor ");
            }
            jTextFieldGorev_No.setText(null);
            jComboBoxGorevTipi.setSelectedIndex(0);
            jComboBoxSurec.setSelectedIndex(0);
            jComboBoxOncelik.setSelectedIndex(0);
            jTextField_konu.setText(null);
            jTextAreanot.setText(null);
            jComboBoxPersonel.setSelectedIndex(0);
            jComboBoxDepartman.setSelectedIndex(0);
        } catch (SQLIntegrityConstraintViolationException ex) {
            jLabelhata.setForeground(Color.red);
            jLabelhata.setText("Bu numarayla farklı kaydınız vardır");
        } catch (NumberFormatException ex) {
            jLabelhata.setForeground(Color.red);
            jLabelhata.setText("Lütfen geçerli görev numara giriniz");
        } catch (SQLException ex) {
            Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonKaydetActionPerformed

    /**
     *
     * @param date
     * @param time
     * @return
     */
    public static java.sql.Date Date() {
        java.util.Calendar cal = Calendar.getInstance();
        java.util.Date utilDate = jCalendar2.getDate(); // your util date
        cal.setTime(utilDate);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        java.sql.Date sqlDate = new java.sql.Date(cal.getTime().getTime());
        return sqlDate;
   }                                             

       
    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        new ana_Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed

    private void jButtonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCikisActionPerformed
        // TODO add your handling code here:
        new giris_ekrani().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeni_gorev_olusturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeni_gorev_olusturma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonCikis;
    private javax.swing.JButton jButtonKaydet;
    public static com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JComboBox jComboBoxDepartman;
    private javax.swing.JComboBox jComboBoxGorevTipi;
    private javax.swing.JComboBox jComboBoxOncelik;
    private javax.swing.JComboBox jComboBoxPersonel;
    private javax.swing.JComboBox jComboBoxSurec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGorev_No;
    private javax.swing.JLabel jLabelGorev_Tipi;
    private javax.swing.JLabel jLabelOncelik;
    private javax.swing.JLabel jLabelSurec;
    private javax.swing.JLabel jLabel_Konu;
    private javax.swing.JLabel jLabel_Tamamlama;
    private javax.swing.JLabel jLabel_not;
    private javax.swing.JLabel jLabelhata;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreanot;
    private javax.swing.JTextField jTextFieldGorev_No;
    private javax.swing.JTextField jTextField_konu;
    // End of variables declaration//GEN-END:variables
}
